BUYERS = [
    # Format: [Company, Website, Country, Address, DecisionMaker, Designation, Email, Phone, LinkedIn, Instagram, Facebook,
    #          Revenue, Employees, YearsInBusiness, ProductCategories, BuysPlush, FromCountry, BuyFreq, PrivateLabel, OEM,
    #          Seasonal, TargetCustomer, RetailPriceRange, ImportHistory, SupplierCountries, CurrentBrands,
    #          BuyingSignal, IntentScore, WhyBuyNow, PainPoint, BestProduct, ExpectedOrderSize, Urgency]

    ["D.M. Gould Wholesale Ltd", "dmgouldwholesale.co.uk", "United Kingdom",
     "Unit 1 Parkside Business Park, Parkside Road, Kendal, Cumbria LA9 7EN",
     "David Gould", "Director", "info@dmgould.co.uk", "+44 1539 729900",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 5-10M", "20-50", "30+", "Plush Toys, Beach Goods, Santa Grotto Gifts, Giftware",
     "Yes", "China, India", "Monthly", "Yes", "Yes", "Yes - Christmas, Easter, Halloween",
     "UK Retailers, Gift Shops, Farm Attractions", "GBP 3-15",
     "Active importer of plush toys", "China, India, SE Asia", "Own Brand + White Label",
     "One of UK's largest plush importers; seasonal collection cycle; 2000 sq ft showroom",
     97, "Largest UK plush importer actively sourcing for Christmas 2026 & Easter 2027 collections",
     "Supplier diversification beyond China; EN71 compliant sources needed",
     "Santa Grotto Plush Sets, Animal Plush, Seasonal Collections",
     "5,000-20,000 pcs per season", "HIGH - Christmas sourcing window open now"],

    ["Van der Meulen Sneek B.V.", "vandermeulen.com", "Netherlands",
     "Sneek & Harlingen, Friesland, Netherlands",
     "Not Verified", "Purchasing Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "EUR 20-50M", "50-100", "145", "Stuffed Animals, Toys, Games, Baby Toys",
     "Yes", "China, SE Asia", "Continuous", "Yes", "Yes", "Yes",
     "Retailers in NL, Belgium, Germany + 20 countries", "EUR 5-25",
     "145-year importer, 6000+ products", "China, Vietnam, Indonesia", "Little Dutch, Own Brands",
     "#1 stuffed animal wholesaler in Netherlands; 6000+ SKU range; serves 23 countries",
     96, "Expanding distribution to 23 countries; needs diversified supply base",
     "China dependency risk; need EN71+CE certified alternatives from India",
     "Baby Plush, Infant Toys, Premium Gift Plush",
     "10,000-50,000 pcs/year", "HIGH - Continuous replenishment cycle"],

    ["A.B. Gee of Ripley Ltd", "abgee.co.uk", "United Kingdom",
     "Asher Lane Business Park, Asher Lane, Ripley, Derbyshire DE5 3SW",
     "Not Verified", "Director", "sales@abgee.co.uk", "+44 1773 570444",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 20-50M", "40", "49 (est. 1975)", "Plush, Pre-School, Board Games, Outdoor Toys",
     "Yes", "China, SE Asia", "Continuous", "Yes", "Yes", "Yes",
     "UK Retail Chains, Independent Toy Shops", "GBP 5-30",
     "7000+ SKUs, official distributor for Aurora plush", "China, Vietnam", "Aurora, Hasbro, Mattel, Funko",
     "UK's leading toy distributor; 75,000 sq ft facility; 7000+ SKUs; Aurora plush distributor",
     95, "Actively expanding own-brand plush range alongside licensed distribution",
     "Need cost-effective private label plush to compete with direct-import retailers",
     "Animal Plush, Character Plush, Baby Plush",
     "10,000-30,000 pcs/year", "HIGH - Actively sourcing new suppliers"],

    ["AL KHALEEJ AL HADI TRADING LLC", "khaleejtoys.com", "UAE",
     "Al Ras, Deira Dubai, UAE",
     "Not Verified", "General Manager", "sales@khaleejtoys.com", "+971 4-2264107",
     "Not Verified", "instagram.com/khaleejtoys", "Not Verified",
     "AED 10-20M", "20-50", "15+", "Plush Toys, Educational Toys, Gift Toys, Custom Logo Plush",
     "Yes", "China", "Monthly", "Yes", "Yes", "Yes - Ramadan, Eid, National Day",
     "UAE/GCC Retailers, Gift Shops, Corporate", "AED 15-80",
     "Active plush importer for UAE/GCC market", "China", "Own Import + Custom",
     "Largest plush wholesale distributor in UAE; custom logo printing; serves entire GCC",
     95, "UAE retail market booming; custom plush demand for corporate events surging",
     "Over-reliance on China; need faster turnaround for custom orders",
     "Custom Logo Plush, Corporate Mascots, Seasonal Plush (Ramadan/Eid)",
     "5,000-15,000 pcs/order", "HIGH - Eid & National Day sourcing active"],

    ["Puckator Ltd", "puckator.co.uk", "United Kingdom",
     "Liskeard, Cornwall, United Kingdom",
     "Not Verified", "Purchasing Manager", "sales@puckator.co.uk", "+44 1579 321550",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 20-50M", "50-100", "30+", "Gifts, Homeware, Plush Toys (Squidglys), Novelties",
     "Yes", "China, India", "Continuous", "Yes", "Yes", "Yes",
     "UK/EU Retailers, Gift Shops, Online Stores", "GBP 3-20",
     "Active importer with own plush brand Squidglys", "China, India, SE Asia", "Squidglys, Licensed Brands",
     "30+ year wholesale giant; own Squidglys plush brand; national sales team; EU distribution",
     94, "Expanding Squidglys plush range; need new OEM manufacturer for private label plush",
     "Need reliable OEM partner for growing own-brand plush line",
     "Fantasy Plush, Character Plush, Novelty Plush",
     "10,000-50,000 pcs/year", "HIGH - Own brand expansion underway"],

    ["NDA Toys", "nda-toys.com", "United Kingdom",
     "London, United Kingdom",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "linkedin.com/company/nda-toys-wholesale", "Not Verified", "Not Verified",
     "GBP 5-15M", "20-50", "10+", "Plush Toys, Arts & Crafts, Board Games, Sensory Toys",
     "Yes", "China", "Continuous", "Yes", "No", "Yes",
     "UK Retailers, Schools, Museums, Charities, Online Traders", "GBP 2-15",
     "UK's largest online toy wholesaler", "China, SE Asia", "Multiple Brands",
     "UK's largest ONLINE toy wholesaler; serves schools, museums, charities; plush range",
     93, "Online wholesale channel growing rapidly; need diverse plush range at competitive prices",
     "Need EN71-certified supplier with low MOQ for diverse retail customer base",
     "Animal Plush, Baby Plush, Sensory Plush",
     "5,000-20,000 pcs/year", "HIGH - Growing online wholesale demand"],

    ["Jasnor (Australia) Pty Ltd", "jasnor.com.au", "Australia",
     "Sydney, NSW, Australia",
     "Not Verified", "Purchasing Director", "Not Verified", "Not Verified",
     "linkedin.com/company/jasnoranz", "Not Verified", "Not Verified",
     "AUD 20-50M", "30-60", "20+", "Licensed Character Toys, Plush Animals, Baby Toys, Gifts",
     "Yes", "China, USA", "Continuous", "Yes", "Yes", "Yes",
     "AU & NZ Retailers", "AUD 10-40",
     "Australia's leading licensed toy distributor", "China, USA, Europe", "Bunnies by the Bay, Licensed Brands",
     "Australia & NZ's leading wholesale toy/gift distributor; strong plush/baby category",
     93, "Expanding baby/infant plush range; distributes to entire AU/NZ market",
     "Need cost-effective EN71/ASTM certified plush for baby segment",
     "Baby & Infant Plush, Premium Gift Plush, Licensed Plush",
     "5,000-20,000 pcs/year", "HIGH - Baby segment expansion"],

    ["Just Play LLC", "justplayproducts.com", "United States",
     "Dallas, Texas, USA",
     "Not Verified", "VP Sourcing", "Not Verified", "Not Verified",
     "linkedin.com/company/just-play", "Not Verified", "Not Verified",
     "USD 200-500M", "200-500", "15+", "Figures, Playsets, Dolls, Plush",
     "Yes", "China", "Continuous", "Yes", "Yes", "Yes",
     "Mass Market US Retail", "USD 8-25",
     "Global leader in children's consumer goods; actively hiring toy designers for plush",
     "China, Vietnam", "Disney, CoComelon, Blue's Clues, Sesame Street",
     "HIRING toy designers for plush; global leader in licensed plush; mass market distribution",
     94, "Actively hiring plush product development roles - signals new collection launch",
     "Diversifying manufacturing base beyond China; need OEM partner",
     "Character Plush, Baby Plush, Licensed Plush",
     "50,000-200,000 pcs/year", "VERY HIGH - Active hiring = imminent orders"],

    ["edZOOcation (Wildlife Tree)", "edzoocation.com", "United States",
     "Concord, CA, USA",
     "Jenny Curtis", "Founder & Owner", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "facebook.com/edzoocation",
     "USD 1-5M", "5-15", "5+", "Subscription Boxes, Plush Animals, STEAM Activities",
     "Yes", "China", "Monthly", "No", "Yes", "Yes",
     "Parents, Schools, Homeschoolers (Ages 3-12)", "USD 30-45/box",
     "Monthly subscription box with premium plush animal in every box",
     "China", "Wildlife Tree",
     "Plush is CORE product in every box; WBENC certified; 50% profits to conservation",
     94, "Monthly subscription = continuous plush demand; each box needs unique plush animal",
     "Need reliable OEM partner for anatomically accurate endangered species plush",
     "Custom Animal Plush (endangered species), Educational Plush",
     "1,000-5,000 pcs/month", "VERY HIGH - Monthly recurring demand"],

    ["Five Below Inc", "fivebelow.com", "United States",
     "701 Market Street, Suite 300, Philadelphia, PA 19106",
     "Not Verified", "Category Buyer - Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/five-below", "instagram.com/fivebelow", "facebook.com/FiveBelow",
     "USD 3.5B+", "20,000+", "22 (est. 2002)", "Plush, Toys, Games, Tech, Room Decor",
     "Yes", "China", "Continuous + Seasonal", "Yes", "Yes", "Yes",
     "Teens, Tweens, Value Shoppers", "USD 1-5",
     "Massive plush buyer; Squishmallows, seasonal collections; 1800+ stores",
     "China, Vietnam", "Squishmallows, Pillow Pets, Pokemon, Hello Kitty",
     "1800+ stores; aggressive expansion; huge plush section; seasonal rotations; value price point",
     93, "Continuous store expansion (1800+ and growing); massive seasonal plush rotation",
     "Need value-priced plush at scale; supplier diversification",
     "Animal Plush, Fantasy Plush, Seasonal Collections",
     "100,000-500,000 pcs/year", "HIGH - Continuous seasonal rotation"],

    ["Jono Toys B.V.", "jono-toys.nl", "Netherlands",
     "Netherlands",
     "Not Verified", "Buyer/Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "EUR 5-15M", "10-30", "10+", "Toys, Plush, Outdoor, Games",
     "Yes", "China, SE Asia", "Continuous", "Yes", "Yes", "Yes",
     "Retailers NL, DE, BE, CH, CZ", "EUR 3-20",
     "Fast-growing wholesaler importing from Far East", "China, SE Asia", "Own Imports + Brands",
     "Fast-growing; imports from Far East; covers NL, DE, BE, CH, CZ; decades of manufacturer contacts",
     92, "Fast growth = expanding product range; needs additional plush suppliers",
     "Need reliable Indian alternative to Chinese suppliers for diversification",
     "Animal Plush, Baby Plush, Seasonal Plush",
     "5,000-20,000 pcs/year", "HIGH - Growth phase"],

    ["Elka Australia", "elka.com.au", "Australia",
     "Australia",
     "Not Verified", "Purchasing Manager", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "AUD 10-30M", "20-50", "25+", "Plush Toys, Stuffed Animals",
     "Yes", "China", "Continuous", "Yes", "Yes", "Yes",
     "AU Retailers, Corporate Entities, NZ, Fiji", "AUD 8-35",
     "One of largest AU plush importers/wholesalers", "China", "Own Brand + Licensed",
     "One of Australia's largest plush importers; serves retailers + corporate; exports to NZ/Fiji",
     92, "Dominant AU plush wholesaler; corporate plush growing; need supplier diversification",
     "China tariff risks; need certified Indian OEM alternative",
     "Animal Plush, Corporate Mascots, Baby Plush",
     "10,000-30,000 pcs/year", "HIGH - Supplier diversification need"],

    ["PlushThis", "plushthis.com", "United States",
     "United States",
     "Not Verified", "Founder", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 1-5M", "5-15", "5+", "Plush Subscription Boxes, Goth/Emo/Art Plush",
     "Yes", "China", "Monthly", "No", "Yes", "Yes",
     "Teens, Adults, Collectors, Niche Communities", "USD 25-60/box",
     "Monthly plush subscription box service", "China", "Own Brand",
     "Unique niche plush subscription; Goth, Emo, Art, Voodoo, Magical Creatures designs",
     91, "Monthly subscription = continuous demand; niche designs need custom OEM partner",
     "Need OEM manufacturer capable of unique artistic plush designs",
     "Fantasy Plush, Custom Character Plush, Art Plush",
     "500-3,000 pcs/month", "HIGH - Monthly recurring orders"],

    ["The Entertainer (Amersham) Ltd", "thetoyshop.com", "United Kingdom",
     "Amersham, Buckinghamshire, UK",
     "Not Verified", "Category Buyer - Plush", "Not Verified", "Not Verified",
     "linkedin.com/company/the-entertainer-toy-shop", "Not Verified", "Not Verified",
     "GBP 200-400M", "2,000+", "43 (est. 1981)", "Toys, Games, Plush, Pre-School",
     "Yes", "China", "Continuous + Seasonal", "Yes", "Yes", "Yes",
     "UK Families, Children", "GBP 5-30",
     "UK's largest independent toy retailer; 170+ stores", "China, Europe", "Major Licensed Brands",
     "UK's largest independent toy retailer; 170+ stores; strong plush section",
     92, "Largest UK independent toy chain; continuous plush sourcing; private label growing",
     "Need competitive private label plush supplier; EN71 certified",
     "Animal Plush, Character Plush, Baby Plush",
     "20,000-100,000 pcs/year", "HIGH - Major retail chain"],

    ["Smyths Toys Group", "smythstoys.com", "United Kingdom",
     "Galway, Ireland (HQ); UK-wide operations",
     "Not Verified", "Buyer - Soft Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/smyths-toys-superstores", "Not Verified", "Not Verified",
     "EUR 1B+", "5,000+", "38 (est. 1986)", "Toys, Games, Plush, Outdoor, Baby",
     "Yes", "China", "Continuous + Seasonal", "Yes", "Yes", "Yes",
     "UK & Ireland Families", "GBP 5-40",
     "Major toy chain UK/Ireland/Germany; acquired Toys R Us UK stores", "China, SE Asia", "All Major Brands",
     "Took over Toys R Us UK; 200+ stores; EUR 1B+ revenue; Germany expansion",
     91, "Aggressive European expansion post-Toys R Us acquisition; huge plush buyer",
     "Need diversified supply chain for EU expansion; EN71/CE compliance critical",
     "Animal Plush, Licensed Character Plush, Baby Plush",
     "50,000-200,000 pcs/year", "HIGH - EU expansion"],

    ["Build-A-Bear Workshop", "buildabear.com", "United States",
     "1954 Innerbelt Business Center Dr, St. Louis, MO 63114",
     "Not Verified", "VP Sourcing & Product Development", "Not Verified", "Not Verified",
     "linkedin.com/company/build-a-bear-workshop", "instagram.com/buildabear", "facebook.com/buildabear",
     "USD 450M+", "4,000+", "27 (est. 1997)", "Customizable Plush Bears & Animals",
     "Yes", "China", "Continuous", "Yes", "Yes", "Yes",
     "Children, Families, Gift Buyers", "USD 15-60",
     "Global plush retail brand; 500+ stores worldwide; subscription program",
     "China, Vietnam", "Own Brand",
     "Global plush specialist; 500+ stores; subscription model; continuous plush demand",
     91, "Subscription model = recurring demand; 500+ stores; expanding online",
     "Need cost-efficient OEM partner for bulk plush shells",
     "Animal Plush, Fantasy Plush, Custom Plush Shells",
     "100,000-500,000+ pcs/year", "HIGH - Core business is plush"],

    ["Dormar Indents Pty Ltd", "dormar.com.au", "Australia",
     "Australia",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "AUD 10-20M", "20-40", "79 (est. 1945)", "Plush Toys, Party Supplies, Giftware, Novelties",
     "Yes", "China", "Continuous", "Yes", "No", "Yes",
     "AU Retailers, Party Shops, Gift Stores", "AUD 5-25",
     "One of AU's largest plush/party wholesalers since 1945", "China", "Own Import + Brands",
     "79-year-old Australian wholesaler; major plush and party supplies distributor",
     90, "Long-established wholesaler with continuous plush demand",
     "Aging Chinese supply base; looking for competitive alternatives",
     "Animal Plush, Novelty Plush, Party Plush",
     "5,000-15,000 pcs/year", "MEDIUM-HIGH"],

    ["ToysLink Pty Ltd", "toyslink.com.au", "Australia",
     "Australia",
     "Not Verified", "Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "AUD 5-10M", "10-20", "10+", "Plush Toys, Wooden Toys, Educational Toys",
     "Yes", "China", "Continuous", "Yes", "No", "Yes",
     "AU & NZ Retailers", "AUD 5-20",
     "Bulk plush specialist for AU/NZ market", "China", "Own Import",
     "Bulk plush specialist; wholesale to AU & NZ retailers",
     90, "Growing demand for bulk plush in AU/NZ",
     "Need competitive pricing from India; EN71/ASTM certified",
     "Animal Plush, Baby Plush",
     "5,000-15,000 pcs/year", "MEDIUM-HIGH"],

    ["4imprint Group plc", "4imprint.com", "United States",
     "101 Commerce Street, Oshkosh, WI 54901, USA",
     "Not Verified", "Product Manager - Plush", "Not Verified", "Not Verified",
     "linkedin.com/company/4imprint", "Not Verified", "Not Verified",
     "USD 1.3B+", "1,500+", "39 (est. 1985)", "Promotional Products, Corporate Gifts, Branded Merchandise",
     "Yes", "China, India", "Continuous", "Yes", "Yes", "No",
     "Corporate Clients, Event Organizers, Schools", "USD 3-15",
     "World's largest promotional products company", "China, India, Bangladesh", "Own Brand + Custom",
     "World's largest promo products company; custom plush for corporate clients; USD 1.3B revenue",
     91, "Massive corporate gift market; custom plush mascots in high demand",
     "Need reliable OEM for custom corporate mascots and branded plush",
     "Corporate Mascots, Custom Logo Plush, Promotional Plush",
     "20,000-100,000 pcs/year", "HIGH - Continuous corporate demand"],

    ["MuzeMerch", "muzemerch.com", "United States",
     "United States",
     "Not Verified", "Buyer/Partnerships", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 5-20M", "10-30", "5+", "Zoo/Aquarium/Museum Gift Shop Merchandise, Plush",
     "Yes", "China", "Continuous", "No", "Yes", "Yes",
     "Zoo, Aquarium, Museum, Science Center Gift Shops", "USD 8-30",
     "Marketplace for zoo/aquarium/museum merch; eco plush a core category",
     "China, Vietnam", "Partner Venue Brands",
     "Marketplace supplying 50+ zoo/aquarium/museum gift shops; eco plush core product",
     91, "Growing partner venue network; each new venue needs plush inventory",
     "Need eco-friendly plush with recycled materials; EN71/ASTM certified",
     "Animal Plush (zoo/aquarium species), Eco-Friendly Plush",
     "5,000-20,000 pcs/year", "HIGH - Growing venue network"],

    ["Hot Topic Inc", "hottopic.com", "United States",
     "City of Industry, California, USA",
     "Not Verified", "Buyer - Plush & Collectibles", "Not Verified", "Not Verified",
     "linkedin.com/company/hot-topic", "instagram.com/hottopic", "facebook.com/hottopic",
     "USD 800M+", "10,000+", "36 (est. 1988)", "Pop Culture, Anime, Character Plush, Apparel",
     "Yes", "China", "Continuous + Convention Season", "Yes", "Yes", "Yes",
     "Teens, Young Adults, Pop Culture Fans", "USD 10-35",
     "Major pop culture retailer; anime/character plush top seller; 700+ stores",
     "China, Vietnam", "Funko, Squishmallows, Anime Brands",
     "700+ stores; anime/character plush massively popular; pop culture plush leader",
     90, "Anime & character plush trending hard; continuous new licensed releases",
     "Need fast-turnaround OEM for licensed character plush",
     "Character Plush, Anime Plush, Fantasy Plush",
     "50,000-200,000 pcs/year", "HIGH - Pop culture plush trending"],

    ["Funko Inc", "funko.com", "United States",
     "2802 Wetmore Avenue, Everett, WA 98201",
     "Not Verified", "VP Product Development", "Not Verified", "Not Verified",
     "linkedin.com/company/funko", "instagram.com/originalfunko", "facebook.com/originalfunko",
     "USD 1B+", "1,000+", "26 (est. 1998)", "Pop Vinyl, Plush, Action Figures, Collectibles",
     "Yes", "China, Vietnam", "Continuous", "Yes", "Yes", "Yes",
     "Collectors, Pop Culture Fans, Gift Buyers", "USD 10-30",
     "Major collectibles company expanding plush line", "China, Vietnam", "Funko Pop!, SuperCute Plush",
     "Billion-dollar collectibles brand; expanding SuperCute Plush line; global distribution",
     90, "Aggressively expanding plush product line; need additional OEM capacity",
     "Need reliable OEM for expanding plush product lines",
     "Character Plush, Licensed Plush, Collectible Plush",
     "50,000-200,000 pcs/year", "HIGH - Plush line expansion"],

    ["Aldi (ALDI Einkauf SE)", "aldi.com", "Germany",
     "Essen, Germany (HQ); Global operations",
     "Not Verified", "Buyer - Seasonal/Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/aldi-sued", "Not Verified", "Not Verified",
     "EUR 100B+", "100,000+", "60+", "Grocery, Seasonal Toys, Plush (Aldi Finds)",
     "Yes", "China", "Seasonal (4-6x/year)", "Yes", "No", "Yes - Christmas, Easter, Back-to-School",
     "Value-conscious families", "USD/EUR 5-15",
     "Seasonal plush collections sell out fast (Little Town, Toy Story, Classic Pooh)",
     "China", "Little Town, Licensed Brands",
     "Global retail giant; seasonal plush sell out immediately; 10,000+ stores worldwide",
     90, "Seasonal plush collections in huge demand; sell-out track record",
     "Need competitive private label plush manufacturer; child-safe; EN71/CE",
     "Seasonal Plush Collections, Baby Plush, Character Plush",
     "100,000-500,000 pcs/season", "HIGH - Seasonal sourcing cycle"],

    ["Dynamic Gift Canada", "dynamicgift.ca", "Canada",
     "Canada",
     "Not Verified", "Sales Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "CAD 5-15M", "10-30", "15+", "Corporate Gifts, Promotional Products, Branded Plush",
     "Yes", "China", "Continuous", "Yes", "Yes", "No",
     "Corporate Clients, Event Organizers", "CAD 5-20",
     "Canadian corporate gift distributor with plush range", "China", "Custom + Brands",
     "Major Canadian promo products distributor; custom branded plush for corporate clients",
     89, "Corporate events rebounding post-COVID; plush mascot demand rising",
     "Need OEM partner for branded custom plush with quick turnaround",
     "Corporate Mascots, Custom Logo Plush, Promotional Plush",
     "2,000-10,000 pcs/year", "MEDIUM-HIGH"],

    ["Garrett Specialties", "garrettspecialties.com", "United States",
     "United States",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 5-10M", "10-20", "20+", "Promotional Products, Stuffed Animals, Corporate Gifts",
     "Yes", "China", "Continuous", "Yes", "Yes", "No",
     "Corporate Clients, Schools, Healthcare", "USD 3-15",
     "Promo stuffed animals specialist", "China", "Custom",
     "Promotional stuffed animal specialist; customizable plush for corporate sector",
     88, "Growing demand for promotional plush in healthcare and education sectors",
     "Need reliable low-MOQ OEM for diverse custom plush orders",
     "Custom Logo Plush, Promotional Animals, Healthcare Plush",
     "2,000-10,000 pcs/year", "MEDIUM-HIGH"],

    ["Promo Bears USA", "promobearsusa.com", "United States",
     "United States",
     "Not Verified", "Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 2-5M", "5-10", "10+", "Custom Plush, Branded Bears, Event Mascots",
     "Yes", "China, India", "Continuous", "Yes", "Yes", "No",
     "Brands, Sports Teams, Event Organizers", "USD 5-20",
     "Custom mascot plush specialist for brands and events", "China, India", "Custom Only",
     "Specialist in custom branded plush for companies, sports teams, events",
     88, "Corporate event market recovering strongly; custom plush orders rising",
     "Need OEM partner with low MOQ for custom mascot plush",
     "Corporate Mascots, Branded Plush, Event Plush",
     "1,000-5,000 pcs/order", "MEDIUM-HIGH"],

    ["John Lewis Partnership", "johnlewis.com", "United Kingdom",
     "171 Victoria Street, London SW1E 5NN",
     "Not Verified", "Buyer - Children's Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/john-lewis-partnership", "Not Verified", "Not Verified",
     "GBP 10B+", "70,000+", "160+", "Department Store, Premium Toys, Baby, Gifts",
     "Yes", "Multiple", "Continuous + Seasonal", "Yes", "No", "Yes - Christmas",
     "UK Affluent Families", "GBP 10-50",
     "Premium UK department store; strong Christmas plush collection", "Multiple Countries", "Jellycat, Steiff, Own Label",
     "Premium UK retailer; Christmas plush collection is major revenue driver; quality-focused",
     89, "Christmas 2026 plush sourcing underway; premium quality required",
     "Need premium-quality plush at competitive price; EN71 certified",
     "Premium Gift Plush, Baby & Infant Plush, Christmas Collections",
     "10,000-50,000 pcs/season", "HIGH - Christmas sourcing window"],

    ["Flying Tiger Copenhagen", "flyingtiger.com", "Denmark",
     "Copenhagen, Denmark (HQ); Global stores",
     "Not Verified", "Product Manager - Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/flying-tiger-copenhagen", "Not Verified", "Not Verified",
     "DKK 5B+", "5,000+", "29 (est. 1995)", "Design Products, Toys, Plush, Novelties, Gifts",
     "Yes", "China", "Seasonal Rotations", "Yes", "No", "Yes",
     "Young Adults, Design Lovers, Gift Buyers", "EUR 3-10",
     "Global design retail chain; 900+ stores; seasonal plush rotations", "China", "Own Brand Only",
     "900+ stores globally; 100% private label; seasonal product rotations every 2 weeks",
     90, "Bi-weekly product rotation means continuous new plush designs needed",
     "Need agile OEM partner for frequent new plush designs at value pricing",
     "Novelty Plush, Fantasy Plush, Seasonal Collections",
     "20,000-100,000 pcs/year", "HIGH - Continuous rotation cycle"],

    ["HEMA B.V.", "hema.com", "Netherlands",
     "Amsterdam, Netherlands",
     "Not Verified", "Buyer - Children's", "Not Verified", "Not Verified",
     "linkedin.com/company/hema", "Not Verified", "Not Verified",
     "EUR 1B+", "10,000+", "97 (est. 1926)", "Retail, Toys, Baby, Home, Food",
     "Yes", "China", "Seasonal + Continuous", "Yes", "No", "Yes",
     "Dutch/EU Families, Children", "EUR 3-15",
     "Major Dutch retailer; 700+ stores; strong private label toy/plush range", "China, India", "HEMA Own Brand",
     "700+ stores NL/EU; 100% private label; strong baby/children's plush category",
     90, "Private label only = always sourcing; baby plush category growing",
     "Need EN71/CE certified OEM with private label capability",
     "Baby Plush, Animal Plush, Seasonal Collections",
     "20,000-80,000 pcs/year", "HIGH - PL-only retailer"],

    ["Søstrene Grene", "sostrenegrene.com", "Denmark",
     "Aarhus, Denmark",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "linkedin.com/company/sostrene-grene", "Not Verified", "Not Verified",
     "DKK 2B+", "2,000+", "50+", "Home Decor, Gifts, Children's, Seasonal, Plush",
     "Yes", "China", "Seasonal", "Yes", "No", "Yes - Christmas, Easter, Spring",
     "Design-conscious consumers, Gift Buyers", "EUR 3-12",
     "Scandinavian lifestyle chain; 300+ stores; seasonal plush collections", "China", "Own Brand",
     "300+ stores; Scandinavian design aesthetic; seasonal plush collections; private label only",
     89, "Seasonal plush collections are customer favorites; expanding store count",
     "Need design-led OEM partner for Scandinavian-aesthetic plush",
     "Premium Gift Plush, Seasonal Collections, Baby Plush",
     "5,000-20,000 pcs/season", "MEDIUM-HIGH - Seasonal sourcing"],

    ["San Diego Zoo Wildlife Alliance", "zoo.sandiegozoo.org", "United States",
     "2920 Zoo Drive, San Diego, CA 92101",
     "Not Verified", "Merchandise Buyer", "Not Verified", "Not Verified",
     "linkedin.com/company/san-diego-zoo-wildlife-alliance", "instagram.com/sandiegozoo", "facebook.com/SanDiegoZoo",
     "USD 300M+", "3,000+", "100+", "Zoo Merchandise, Plush Animals, Apparel, Gifts",
     "Yes", "China", "Continuous + Seasonal", "No", "Yes", "Yes",
     "Zoo Visitors, Conservation Supporters, Gift Buyers", "USD 10-40",
     "One of world's most visited zoos; massive gift shop operation", "China, Vietnam", "San Diego Zoo Brand",
     "World-famous zoo; massive gift shop revenue; plush animals are #1 seller",
     89, "Post-COVID visitor numbers exceeding pre-pandemic; gift shop revenue booming",
     "Need eco-friendly plush; conservation-themed; recycled materials preferred",
     "Animal Plush (zoo species), Eco-Friendly Plush",
     "5,000-20,000 pcs/year", "MEDIUM-HIGH"],

    ["Merlin Entertainments", "merlinentertainments.biz", "United Kingdom",
     "Poole, Dorset, United Kingdom",
     "Not Verified", "Head of Merchandise Procurement", "Not Verified", "Not Verified",
     "linkedin.com/company/merlin-entertainments", "Not Verified", "Not Verified",
     "GBP 5B+", "30,000+", "25+", "Theme Park Merchandise, Plush, Apparel, Gifts",
     "Yes", "China", "Continuous", "Yes", "Yes", "Yes",
     "Theme Park Visitors Worldwide", "GBP 8-30",
     "LEGOLAND, Sea Life, Madame Tussauds, Alton Towers; 130+ attractions globally",
     "China", "LEGO, Own Brands",
     "130+ attractions globally; Sea Life aquariums = massive plush demand; LEGOLAND plush",
     90, "130 attractions worldwide need plush inventory; Sea Life aquariums especially",
     "Need bulk animal plush for aquarium/zoo attractions; EN71/CE certified",
     "Animal Plush (aquatic species), Fantasy Plush, Character Plush",
     "50,000-200,000 pcs/year", "HIGH - 130+ venue network"],

    ["SeaWorld Entertainment", "seaworld.com", "United States",
     "9205 South Park Center Loop, Orlando, FL 32819",
     "Not Verified", "Merchandise Buyer", "Not Verified", "Not Verified",
     "linkedin.com/company/seaworld-entertainment", "instagram.com/seaworld", "Not Verified",
     "USD 1.8B+", "20,000+", "60+", "Theme Park Merchandise, Plush Marine Animals",
     "Yes", "China", "Continuous + Seasonal", "No", "Yes", "Yes",
     "Theme Park Visitors, Families", "USD 10-40",
     "SeaWorld, Busch Gardens, Sesame Place; plush marine animals top sellers",
     "China", "SeaWorld Brand, Sesame Street",
     "12 theme parks; marine animal plush is top gift shop category",
     89, "Park attendance recovering; merchandise revenue growing; new parks planned",
     "Need marine animal plush; eco-friendly options for conservation messaging",
     "Animal Plush (marine species), Baby Plush, Character Plush",
     "20,000-80,000 pcs/year", "MEDIUM-HIGH"],

    ["Virgin Megastore UAE", "virginmegastore.ae", "UAE",
     "Dubai, UAE",
     "Not Verified", "Category Buyer - Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/virgin-megastore-mena", "Not Verified", "Not Verified",
     "AED 500M+", "1,000+", "20+", "Entertainment, Toys, Plush, Tech, Books",
     "Yes", "Multiple", "Continuous", "Yes", "No", "Yes - Ramadan, Eid",
     "UAE/GCC Middle-to-Upper Class", "AED 30-120",
     "Major MENA entertainment retailer; plush/soft toys category", "Multiple", "Licensed Brands",
     "Leading entertainment retailer in MENA; 50+ stores; growing plush/soft toys section",
     88, "GCC retail market growing; plush & character toys trending in MENA",
     "Need diverse plush supplier with competitive pricing for GCC market",
     "Character Plush, Licensed Plush, Premium Gift Plush",
     "5,000-20,000 pcs/year", "MEDIUM-HIGH"],

    ["Landmark Group (BabyShop/Fun City)", "landmarkgroup.com", "UAE",
     "Dubai, UAE",
     "Not Verified", "Group Buyer - Toys & Baby", "Not Verified", "Not Verified",
     "linkedin.com/company/landmark-group", "Not Verified", "Not Verified",
     "USD 7B+", "50,000+", "50+", "Retail, Baby Products, Toys, Entertainment",
     "Yes", "China, India", "Continuous", "Yes", "Yes", "Yes",
     "GCC Families, Baby Segment", "AED 20-100",
     "GCC's largest retail conglomerate; BabyShop 200+ stores; Fun City entertainment",
     "China, India, SE Asia", "BabyShop, Splash, Home Centre",
     "GCC's largest retailer; 200+ BabyShop stores; strong India sourcing relationship",
     89, "Already sources from India; BabyShop expanding; baby plush in high demand",
     "Existing India sourcing = warm lead; need baby-safe plush manufacturer",
     "Baby & Infant Plush, Gift Plush, Corporate Plush",
     "10,000-50,000 pcs/year", "HIGH - Existing India sourcing link"],

    ["Toys R Us Asia (Fung Retailing)", "toysrus.com.sg", "Singapore",
     "Singapore (regional HQ)",
     "Not Verified", "Regional Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 2B+", "5,000+", "20+", "Toys, Plush, Baby, Games, Outdoor",
     "Yes", "China", "Continuous + Seasonal", "Yes", "Yes", "Yes",
     "Asian Families, Children", "SGD 10-50",
     "Toys R Us operating 400+ stores across Asia", "China, SE Asia", "All Major Toy Brands",
     "400+ stores across Asia; only surviving Toys R Us operation globally; huge plush buyer",
     89, "Sole surviving Toys R Us operation; 400+ stores; aggressive expansion in Asia",
     "Need diversified supply beyond China; competitive plush for Asian tastes",
     "Animal Plush, Character Plush, Baby Plush, Licensed Plush",
     "50,000-200,000 pcs/year", "HIGH - Major Asian toy retailer"],

    ["Whirli Ltd", "whirli.com", "United Kingdom",
     "London, UK",
     "Not Verified", "Founder/CEO", "Not Verified", "Not Verified",
     "linkedin.com/company/whirli", "Not Verified", "Not Verified",
     "GBP 1-5M", "10-30", "5+", "Toy Sharing Subscription, Plush, Educational Toys",
     "Yes", "Multiple", "Monthly", "No", "Yes", "No",
     "UK Families, Eco-Conscious Parents", "GBP 10-25/month",
     "Toy sharing subscription; actively hiring tech + sourcing staff", "Multiple", "Major Brands + Own Curation",
     "Innovative toy sharing subscription; actively HIRING = growth phase; plush is key category",
     88, "Active hiring signals rapid growth; need plush inventory for expanding subscriber base",
     "Need durable, washable plush for sharing/rental model; safety-certified",
     "Animal Plush, Baby Plush, Durable Plush",
     "2,000-10,000 pcs/year", "MEDIUM-HIGH"],

    ["Costco Wholesale", "costco.com", "United States",
     "999 Lake Drive, Issaquah, WA 98027",
     "Not Verified", "Buyer - Seasonal/Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/costco-wholesale", "Not Verified", "Not Verified",
     "USD 250B+", "300,000+", "43 (est. 1983)", "Wholesale Retail, Seasonal Toys, Plush",
     "Yes", "China", "Seasonal (3-4x/year)", "Yes", "No", "Yes - Christmas, Valentine's, Easter",
     "Members, Value-Conscious Families", "USD 10-30",
     "Massive seasonal plush buyer; giant plush bears viral sellers", "China, Vietnam", "Licensed + White Label",
     "800+ warehouses globally; seasonal plush (especially giant bears) are viral sellers",
     88, "Giant/oversized plush consistently goes viral; seasonal windows approaching",
     "Need oversized plush manufacturer at scale; child-safe; ASTM certified",
     "Giant/Oversized Plush, Seasonal Collections, Premium Gift Plush",
     "50,000-200,000 pcs/season", "HIGH - Christmas seasonal window"],

    ["Target Corporation", "target.com", "United States",
     "1000 Nicollet Mall, Minneapolis, MN 55403",
     "Not Verified", "Buyer - Toys & Seasonal", "Not Verified", "Not Verified",
     "linkedin.com/company/target", "instagram.com/target", "facebook.com/target",
     "USD 107B+", "400,000+", "62 (est. 1962)", "Mass Retail, Toys, Baby, Seasonal, Home",
     "Yes", "China, Vietnam", "Continuous + Seasonal", "Yes", "Yes", "Yes",
     "American Families, All Demographics", "USD 5-25",
     "1,900+ stores; huge plush/stuffed animal section; private label Pillowfort",
     "China, Vietnam, Bangladesh", "Pillowfort (PL), Squishmallows, Licensed",
     "1,900+ stores; Bullseye mascot plush; private label Pillowfort; massive buyer",
     88, "Continuous replenishment + seasonal rotations; private label expansion",
     "Need ASTM-certified private label plush manufacturer with scale",
     "Animal Plush, Baby Plush, Seasonal Collections, Private Label",
     "200,000-1,000,000 pcs/year", "HIGH - Massive buyer (hard to break in)"],

    ["Dollar Tree Inc", "dollartree.com", "United States",
     "500 Volvo Parkway, Chesapeake, VA 23320",
     "Not Verified", "Category Manager - Seasonal", "Not Verified", "Not Verified",
     "linkedin.com/company/dollar-tree", "Not Verified", "Not Verified",
     "USD 30B+", "200,000+", "38 (est. 1986)", "Value Retail, Seasonal Toys, Plush",
     "Yes", "China", "Seasonal", "Yes", "No", "Yes",
     "Value-Conscious Consumers", "USD 1.25-5",
     "16,000+ stores (Dollar Tree + Family Dollar); seasonal plush at extreme value",
     "China", "Unbranded + Licensed",
     "16,000+ stores; extreme-value plush at $1.25-$5 price point; massive volume",
     87, "Massive volume buyer; seasonal plush rotations; need lowest-cost sourcing",
     "Need ultra-low-cost plush manufacturer; India pricing advantage",
     "Value Plush, Mini Plush, Seasonal Collections",
     "500,000-2,000,000 pcs/year", "MEDIUM - Very price-sensitive"],

    ["Spencer Gifts LLC", "spencersonline.com", "United States",
     "6826 Black Horse Pike, Egg Harbor Township, NJ 08234",
     "Not Verified", "Buyer - Novelties", "Not Verified", "Not Verified",
     "linkedin.com/company/spencer-gifts", "Not Verified", "Not Verified",
     "USD 500M+", "5,000+", "77 (est. 1947)", "Novelties, Gifts, Character Plush, Pop Culture",
     "Yes", "China", "Continuous", "Yes", "Yes", "Yes",
     "Teens, Young Adults, Gift Buyers", "USD 10-30",
     "600+ mall stores; character/novelty plush strong seller", "China", "Licensed Character Brands",
     "600+ stores; novelty/character plush is key category; pop culture driven",
     87, "Character plush trending; new licensed collections continuously launching",
     "Need fast-turnaround OEM for novelty and character plush",
     "Novelty Plush, Character Plush, Fantasy Plush",
     "20,000-80,000 pcs/year", "MEDIUM-HIGH"],

    ["Learning Express Toys", "learningexpress.com", "United States",
     "United States (franchise network)",
     "Not Verified", "Franchise Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 50-100M (network)", "500+ (network)", "36 (est. 1987)", "Specialty Toys, Educational, Plush",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Parents, Educators, Gift Buyers", "USD 10-35",
     "130+ specialty toy store franchise locations", "Multiple", "Specialty Brands",
     "130+ specialty toy stores; curated plush selection; quality-focused buying",
     86, "Quality specialty retailer; willing to source unique plush products",
     "Need unique, quality plush not available in mass market",
     "Premium Animal Plush, Educational Plush, Baby Plush",
     "5,000-15,000 pcs/year", "MEDIUM"],

    ["Fat Brain Toys", "fatbraintoys.com", "United States",
     "Elkhorn, Nebraska, USA",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "linkedin.com/company/fat-brain-toys", "Not Verified", "Not Verified",
     "USD 20-50M", "50-100", "20+", "Educational Toys, Specialty, Plush, STEM",
     "Yes", "Multiple", "Continuous", "No", "Yes", "No",
     "Parents, Educators, Gift Buyers", "USD 10-40",
     "Award-winning specialty toy retailer; curated plush selection", "Multiple", "Specialty Brands",
     "Award-winning online specialty retailer; curated plush for discerning buyers",
     85, "Growing online sales; need unique educational/premium plush",
     "Need innovative plush with educational angle; quality-first",
     "Educational Plush, Baby Plush, Premium Animal Plush",
     "2,000-8,000 pcs/year", "MEDIUM"],

    ["Lovevery", "lovevery.com", "United States",
     "Boise, Idaho, USA",
     "Not Verified", "VP Product", "Not Verified", "Not Verified",
     "linkedin.com/company/lovevery", "instagram.com/lovevery", "Not Verified",
     "USD 100-200M", "200-500", "8 (est. 2017)", "Baby & Toddler Subscription, Play Kits",
     "Yes", "China", "Monthly/Quarterly", "Yes", "Yes", "No",
     "New Parents, Montessori-aligned Families", "USD 36-48/kit",
     "Premium baby subscription box; plush components in play kits", "China, Vietnam", "Own Brand",
     "Fast-growing baby subscription brand; plush in developmental play kits",
     88, "Rapid growth trajectory; subscription model = recurring plush demand",
     "Need developmental-appropriate baby plush; organic/safe materials",
     "Baby & Infant Plush, Sensory Plush, Developmental Plush",
     "5,000-20,000 pcs/quarter", "HIGH - Fast-growing subscription"],

    ["KiwiCo", "kiwico.com", "United States",
     "Mountain View, California, USA",
     "Not Verified", "Product Manager", "Not Verified", "Not Verified",
     "linkedin.com/company/kiwico", "instagram.com/kaborivekids", "Not Verified",
     "USD 100-200M", "200-500", "13 (est. 2011)", "STEM Subscription Boxes, Craft Kits",
     "Yes - Koala Crate line", "China", "Monthly", "Yes", "Yes", "No",
     "Parents, Educators (Ages 0-14)", "USD 20-40/box",
     "Leading STEM subscription box; Koala Crate (0-2 years) includes plush elements",
     "China", "Own Brand",
     "Major kids subscription brand; baby/toddler line includes plush; 40M+ crates shipped",
     87, "40M+ crates shipped; baby line growing; plush components needed",
     "Need baby-safe plush components for subscription kits; ASTM certified",
     "Baby & Infant Plush, Sensory Plush, Educational Plush",
     "5,000-15,000 pcs/quarter", "MEDIUM-HIGH"],

    ["Uncommon Goods", "uncommongoods.com", "United States",
     "Brooklyn, New York, USA",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "linkedin.com/company/uncommongoods", "Not Verified", "Not Verified",
     "USD 100-200M", "200-500", "25 (est. 1999)", "Unique Gifts, Handmade, Sustainable Products",
     "Yes", "Multiple", "Continuous + Seasonal", "No", "Yes", "Yes",
     "Gift Buyers, Eco-Conscious Consumers", "USD 15-50",
     "Unique/artisan gift platform; sustainable plush products in catalog", "Multiple", "Independent Brands",
     "Curated unique gift platform; B Corp certified; sustainable products preferred",
     86, "Growing sustainable product range; eco-friendly plush in demand",
     "Need sustainable, handmade-look plush; recycled/organic materials",
     "Premium Gift Plush, Eco-Friendly Plush, Artisan Plush",
     "1,000-5,000 pcs/year", "MEDIUM"],

    ["1-800-Flowers.com", "1800flowers.com", "United States",
     "One Old Country Road, Suite 500, Carle Place, NY 11514",
     "Not Verified", "Category Manager - Gifts", "Not Verified", "Not Verified",
     "linkedin.com/company/1-800-flowers", "Not Verified", "Not Verified",
     "USD 2B+", "10,000+", "50+", "Flowers, Gift Baskets, Plush Add-ons, Gourmet",
     "Yes", "China", "Continuous + Seasonal", "Yes", "Yes", "Yes - Valentine's, Mother's Day, Christmas",
     "Gift Buyers, All Demographics", "USD 10-30",
     "Major gift company; plush add-ons with flower/gift basket orders", "China", "Own Brand + Licensed",
     "Billion-dollar gift company; plush teddy bears are top add-on product; peak seasons",
     87, "Peak seasonal windows (Valentine's, Mother's Day) approaching; plush is core add-on",
     "Need affordable plush add-ons at scale; gift-ready packaging",
     "Gift Plush (bears, animals), Valentine's Collections, Seasonal",
     "20,000-100,000 pcs/year", "HIGH - Seasonal peak approaching"],

    ["Hallmark Cards Inc", "hallmark.com", "United States",
     "2501 McGee Trafficway, Kansas City, MO 64108",
     "Not Verified", "Product Manager - Gifts", "Not Verified", "Not Verified",
     "linkedin.com/company/hallmark", "Not Verified", "Not Verified",
     "USD 4B+", "30,000+", "115+ (est. 1910)", "Greeting Cards, Gifts, Plush, Ornaments",
     "Yes", "China", "Seasonal + Continuous", "Yes", "Yes", "Yes",
     "Gift Buyers, Families, All Demographics", "USD 10-30",
     "Iconic gift brand; plush animals in Gold Crown stores; seasonal collections",
     "China, SE Asia", "Hallmark Brand",
     "Iconic global gift brand; 2,000+ Gold Crown stores; seasonal plush collections",
     87, "Seasonal plush collections (Valentine's, Easter, Christmas) drive traffic",
     "Need seasonal plush supplier at scale; premium quality for brand standards",
     "Seasonal Gift Plush, Premium Plush, Valentine's Bears",
     "50,000-200,000 pcs/year", "HIGH - Large buyer"],

    ["Lidl Stiftung & Co. KG", "lidl.com", "Germany",
     "Neckarsulm, Germany (HQ); Global operations",
     "Not Verified", "Buyer - Non-Food/Seasonal", "Not Verified", "Not Verified",
     "linkedin.com/company/lidl", "Not Verified", "Not Verified",
     "EUR 120B+", "360,000+", "50+", "Grocery, Seasonal Toys, Private Label Plush",
     "Yes", "China", "Seasonal", "Yes", "No", "Yes",
     "Value-Conscious EU Families", "EUR 3-12",
     "Seasonal plush under Playtive brand; 12,000+ stores in 31 countries",
     "China", "Playtive (Own Brand)",
     "12,000+ stores; 31 countries; Playtive plush brand; seasonal collections",
     88, "12,000+ stores worldwide; seasonal plush collections; private label only",
     "Need cost-competitive PL plush manufacturer; EN71/CE critical",
     "Seasonal Plush, Baby Plush, Value Collections",
     "200,000-1,000,000 pcs/season", "HIGH - Volume buyer"],

    ["Keycraft Global", "keycraftglobal.com", "United Kingdom",
     "United Kingdom (HQ); AU, EU offices",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 10-20M", "30-50", "25+", "Wholesale Toys, Plush, Pocket Money Toys, STEM",
     "Yes", "China", "Continuous", "Yes", "Yes", "Yes",
     "UK, AU, EU Retailers, Gift Shops, Museums", "GBP 3-15",
     "Global toy wholesaler; UK, AU operations; plush range", "China, SE Asia", "Own Brand + Licensed",
     "Global wholesale operation (UK/AU/EU); soft plush toys is dedicated category",
     88, "Multi-country wholesale operation; continuous plush sourcing",
     "Need competitive plush supplier across multiple markets; diverse certifications",
     "Animal Plush, Pocket Money Plush, Museum Gift Plush",
     "10,000-30,000 pcs/year", "MEDIUM-HIGH"],

    ["William Valentine Pty Ltd", "williamvalentine.com.au", "Australia",
     "Australia",
     "Not Verified", "Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "AUD 5-10M", "10-20", "10+", "Wholesale Plush, Toys, Gifts",
     "Yes", "China", "Continuous", "Yes", "No", "Yes",
     "AU Retailers", "AUD 5-20",
     "Australian wholesale plush distributor", "China", "Own Import",
     "Australian wholesale plush specialist",
     86, "Growing plush demand in AU market",
     "Need competitive alternative to Chinese suppliers",
     "Animal Plush, Baby Plush",
     "3,000-10,000 pcs/year", "MEDIUM"],

    ["Stuffed With Plush Toys", "stuffedwithplushtoys.com", "Australia",
     "Australia",
     "Not Verified", "Owner", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "AUD 2-5M", "5-10", "16+", "Plush Toys, Stuffed Animals from 40+ brands",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "AU Consumers, Gift Buyers", "AUD 10-50",
     "16-year AU plush specialist; 40+ brands", "Multiple Countries", "40+ Global Brands",
     "Trusted AU plush specialist; carries 40+ brands; 16 years in business",
     86, "Expanding brand portfolio; may want to add Indian-made plush line",
     "Need quality plush from new source countries; EN71/ASTM certified",
     "Premium Animal Plush, Baby Plush, Gift Plush",
     "2,000-8,000 pcs/year", "MEDIUM"],

    ["CustomPlush.com (Plush in a Rush)", "customplush.com", "United States",
     "United States",
     "Not Verified", "Sales Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 5-20M", "20-50", "30+", "Custom Plush Manufacturing, OEM, Brand Mascots",
     "Yes", "China", "Continuous", "Yes", "Yes", "No",
     "Brands, Corporations, Event Organizers", "USD 5-25",
     "30+ years custom plush; serves Coca-Cola, FedEx, Amazon, Disney, Macy's",
     "China, Vietnam", "Custom Only",
     "30-year custom plush maker for Fortune 500 brands; may outsource to India for cost",
     88, "Massive client roster (Coca-Cola, Amazon, Disney); may need co-manufacturing",
     "Potential co-manufacturing partner; needs additional production capacity",
     "Corporate Mascots, Branded Plush, Custom Character Plush",
     "10,000-100,000 pcs/year", "HIGH - Potential manufacturing partner"],

    ["Emirates Airlines", "emirates.com", "UAE",
     "Dubai, UAE",
     "Not Verified", "Procurement Manager - Inflight Services", "Not Verified", "Not Verified",
     "linkedin.com/company/emirates", "Not Verified", "Not Verified",
     "USD 35B+", "60,000+", "39 (est. 1985)", "Aviation, Inflight Amenities, Children's Kits",
     "Yes", "Multiple", "Annual Contract", "Yes", "Yes", "No",
     "Child Passengers on Emirates Flights", "N/A - Inflight Amenity",
     "Premium airline; children's activity kits with plush mascots", "Multiple", "Emirates Branded",
     "Premium airline; children receive plush mascots inflight; massive annual orders",
     87, "Annual inflight amenity contract cycle; children's plush kits refreshed yearly",
     "Need branded plush mascots for children's amenity kits; bulk orders",
     "Custom Mascot Plush, Branded Airline Plush",
     "50,000-200,000 pcs/year", "MEDIUM-HIGH - Annual contract cycle"],

    ["Singapore Airlines", "singaporeair.com", "Singapore",
     "Singapore",
     "Not Verified", "Procurement - Inflight Products", "Not Verified", "Not Verified",
     "linkedin.com/company/singapore-airlines", "Not Verified", "Not Verified",
     "USD 15B+", "25,000+", "78 (est. 1947)", "Aviation, Inflight Amenities, Children's Kits",
     "Yes", "Multiple", "Annual Contract", "Yes", "Yes", "No",
     "Child Passengers on SIA Flights", "N/A - Inflight Amenity",
     "World's best airline; children's amenity kits with plush", "Multiple", "SIA Branded",
     "World's best airline; premium children's amenity kits with plush gifts",
     86, "Annual children's amenity refresh; premium quality required",
     "Need premium-quality branded plush; small MOQ per design",
     "Custom Mascot Plush, Premium Branded Plush",
     "20,000-80,000 pcs/year", "MEDIUM"],

    ["Qantas Airways", "qantas.com", "Australia",
     "Sydney, Australia",
     "Not Verified", "Procurement - Onboard Products", "Not Verified", "Not Verified",
     "linkedin.com/company/qantas", "Not Verified", "Not Verified",
     "AUD 20B+", "25,000+", "104 (est. 1920)", "Aviation, Inflight Amenities",
     "Yes", "Multiple", "Annual Contract", "Yes", "Yes", "No",
     "Child Passengers on Qantas Flights", "N/A - Inflight Amenity",
     "Australian flag carrier; Joey plush mascot for children", "Multiple", "Qantas Branded",
     "Australia's flag carrier; iconic Joey plush mascot for children's kits",
     86, "Annual amenity refresh cycle; iconic Joey plush mascot program",
     "Need custom mascot plush; Australian animal themes",
     "Custom Mascot Plush (kangaroo/koala), Branded Airline Plush",
     "10,000-30,000 pcs/year", "MEDIUM"],

    ["Turkish Airlines", "turkishairlines.com", "Turkey",
     "Istanbul, Turkey",
     "Not Verified", "Procurement Manager", "Not Verified", "Not Verified",
     "linkedin.com/company/turkish-airlines", "Not Verified", "Not Verified",
     "USD 20B+", "40,000+", "93 (est. 1933)", "Aviation, Inflight Amenities",
     "Yes", "Multiple", "Annual Contract", "Yes", "Yes", "No",
     "Child Passengers", "N/A - Inflight Amenity",
     "Major global airline; children's amenity kits", "Multiple", "TK Branded",
     "Largest airline by destinations; children's amenity program; India proximity advantage",
     85, "Flies to most countries; children's amenity program; India is close supplier",
     "Need branded plush for children's amenity kits; India logistics advantage",
     "Custom Mascot Plush, Branded Airline Plush",
     "20,000-50,000 pcs/year", "MEDIUM"],

    ["Smithsonian Institution", "si.edu", "United States",
     "Washington, DC, USA",
     "Not Verified", "Merchandise Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 1.5B+ (budget)", "6,000+", "178 (est. 1846)", "Museum Merchandise, Educational Toys, Plush",
     "Yes", "Multiple", "Continuous + Seasonal", "No", "Yes", "Yes",
     "Museum Visitors, Families, Educators", "USD 10-30",
     "World's largest museum complex; 30M+ visitors/year; plush in gift shops",
     "Multiple", "Smithsonian Branded",
     "World's largest museum complex; 30M+ annual visitors; gift shop plush is top seller",
     86, "30M+ visitors = massive gift shop traffic; plush animals are top sellers",
     "Need educational/nature-themed plush; eco-friendly preferred",
     "Animal Plush (dinosaurs, space, nature), Educational Plush",
     "5,000-20,000 pcs/year", "MEDIUM-HIGH"],

    ["Natural History Museum London", "nhm.ac.uk", "United Kingdom",
     "Cromwell Road, South Kensington, London SW7 5BD",
     "Not Verified", "Retail Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 100M+ (budget)", "1,000+", "143 (est. 1881)", "Museum Merchandise, Plush, Educational",
     "Yes", "Multiple", "Continuous + Seasonal", "No", "Yes", "Yes",
     "Museum Visitors, UK Families, Tourists", "GBP 8-25",
     "5M+ visitors/year; dinosaur & animal plush are top gift shop items",
     "Multiple", "NHM Branded",
     "5M+ annual visitors; iconic dinosaur plush is best-seller; premium gift shop",
     87, "Dinosaur and animal plush consistently best-selling gift shop items",
     "Need accurate animal/dinosaur plush; EN71 certified; eco-friendly",
     "Animal Plush (dinosaurs, wildlife), Educational Plush",
     "3,000-10,000 pcs/year", "MEDIUM-HIGH"],

    ["Chester Zoo Enterprises", "chesterzoo.org", "United Kingdom",
     "Upton-by-Chester, Chester CH2 1EU, UK",
     "Not Verified", "Retail Manager", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 50-100M", "500+", "93 (est. 1931)", "Zoo Merchandise, Plush Animals, Gifts",
     "Yes", "Multiple", "Continuous + Seasonal", "No", "Yes", "Yes",
     "Zoo Visitors, UK Families", "GBP 5-20",
     "UK's most visited zoo; 2M+ visitors/year; plush animal gift shop", "Multiple", "Chester Zoo Branded",
     "UK's most visited zoo; 2M+ visitors; gift shop plush animals top seller",
     86, "2M+ visitors generating strong gift shop revenue; plush is #1 category",
     "Need realistic animal plush; EN71 certified; eco-friendly materials",
     "Animal Plush (zoo species), Eco-Friendly Plush",
     "2,000-8,000 pcs/year", "MEDIUM"],

    ["London Zoo (ZSL)", "zsl.org", "United Kingdom",
     "Regent's Park, London NW1 4RY, UK",
     "Not Verified", "Retail Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 80-120M", "500+", "196 (est. 1828)", "Zoo Merchandise, Plush, Conservation",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Zoo Visitors, London Tourists, Families", "GBP 5-25",
     "World's oldest scientific zoo; major gift shop; plush animals", "Multiple", "ZSL Branded",
     "World's oldest scientific zoo; iconic London attraction; conservation-themed plush",
     85, "Conservation messaging growing; eco-friendly plush in demand",
     "Need conservation-themed plush; recycled materials; EN71 certified",
     "Animal Plush (endangered species), Eco-Friendly Plush",
     "2,000-5,000 pcs/year", "MEDIUM"],

    ["Taronga Conservation Society", "taronga.org.au", "Australia",
     "Bradleys Head Road, Mosman NSW 2088, Australia",
     "Not Verified", "Retail Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "AUD 50-80M", "400+", "108 (est. 1916)", "Zoo Merchandise, Plush Australian Animals",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Zoo Visitors, Australian Families, Tourists", "AUD 10-35",
     "Sydney's iconic zoo; Australian animal plush top sellers", "China, AU", "Taronga Branded",
     "Iconic Australian zoo; koala/kangaroo plush are best sellers; eco focus",
     85, "Australian animal plush consistently top sellers; eco-friendly trend growing",
     "Need Australian animal plush (koala, kangaroo, platypus); eco materials",
     "Animal Plush (Australian species), Eco-Friendly Plush",
     "2,000-5,000 pcs/year", "MEDIUM"],

    ["Logotech Inc", "logotech.com", "United States",
     "United States",
     "Not Verified", "Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 5-10M", "10-20", "15+", "Custom Branded Products for Zoos/Museums/Aquariums",
     "Yes", "China", "Continuous", "Yes", "Yes", "No",
     "Zoos, Aquariums, Museums", "USD 8-25",
     "Custom-branded products specialist for institutional gift shops", "China", "Custom Only",
     "Specialist supplier to zoo/aquarium/museum gift shops; custom branded plush",
     87, "Growing venue client base; need OEM plush manufacturer partner",
     "Need custom plush OEM with low MOQ for institutional branded products",
     "Custom Animal Plush, Branded Gift Shop Plush",
     "5,000-20,000 pcs/year", "MEDIUM-HIGH"],

    ["Grossiste-Jeux.be", "grossiste-jeux.be", "Belgium",
     "Belgium",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "EUR 2-5M", "5-10", "10+", "Wholesale Games, Toys, Plush, Giftware",
     "Yes", "China", "Continuous", "Yes", "No", "Yes",
     "Belgian/EU Retailers", "EUR 3-15",
     "Belgian toy/plush wholesaler", "China", "Multiple Brands",
     "Belgian wholesale operation; plush is dedicated category; flexible order quantities",
     85, "Growing Belgian market; need diverse plush range",
     "Need EN71/CE certified plush at competitive EU pricing",
     "Animal Plush, Novelty Plush, Seasonal Plush",
     "2,000-8,000 pcs/year", "MEDIUM"],

    ["Eleganter Toys", "eleganter.com.au", "Australia",
     "Australia",
     "Not Verified", "Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "AUD 2-5M", "5-10", "10+", "Wooden Toys, Baby Toys, Educational, Plush",
     "Yes", "Multiple", "Continuous", "No", "Yes", "No",
     "AU Parents, Educators", "AUD 10-30",
     "Australian toy supplier with in-house brands; imports quality international toys",
     "Multiple Countries", "Kaper Kidz, Koala Dream, Wanborns",
     "Australian toy importer with in-house brands; looking for quality international toys",
     84, "Expanding product range; may add plush to in-house brand portfolio",
     "Need quality plush manufacturer for potential own-brand launch",
     "Baby Plush, Educational Plush, Animal Plush",
     "1,000-5,000 pcs/year", "MEDIUM"],

    ["Stuffed Animal House Ltd", "stuffedanimalhouse.com", "Canada",
     "Canada",
     "Not Verified", "Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "CAD 2-5M", "5-15", "15+", "Plush Toys, Custom Corporate Plush, Embroidery",
     "Yes", "China, India", "Continuous", "Yes", "Yes", "No",
     "Canadian Retailers, Corporate Clients", "CAD 5-25",
     "Canadian plush specialist with in-house embroidery/customization", "China, India", "Own Brand + Custom",
     "Canadian plush specialist; in-house customization; corporate clients",
     85, "In-house customization capability; corporate plush demand growing",
     "Need plush shells/blanks for in-house customization; India sourcing existing",
     "Blank Plush for Customization, Corporate Mascots",
     "2,000-8,000 pcs/year", "MEDIUM-HIGH - Already sources from India"],

    ["FNP (Ferns N Petals)", "fnp.ae", "UAE",
     "Dubai, UAE (ME operations); India HQ",
     "Not Verified", "Category Manager", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 100-200M", "2,000+", "25+", "Gifts, Flowers, Plush, Hampers",
     "Yes", "India, China", "Continuous + Seasonal", "Yes", "Yes", "Yes",
     "Gift Buyers across India, UAE, Singapore, Malaysia, Qatar", "USD 10-30",
     "Major gifting brand; plush bears/animals as add-on gifts", "India, China", "FNP Branded",
     "Major gifting brand in India/ME; plush is top add-on; ALREADY sources from India",
     90, "Already sourcing from India; expanding in UAE/GCC; plush is core gift add-on",
     "Existing India relationship; need premium plush manufacturer partner",
     "Gift Plush (bears, animals), Seasonal Plush, Premium Plush",
     "10,000-50,000 pcs/year", "VERY HIGH - India-based, warm lead"],

    ["Shedd Aquarium", "sheddaquarium.org", "United States",
     "1200 S DuSable Lake Shore Dr, Chicago, IL 60605",
     "Not Verified", "Retail Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 100M+", "500+", "96 (est. 1930)", "Aquarium Merchandise, Plush Marine Animals",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Aquarium Visitors, Chicago Tourists", "USD 10-30",
     "One of world's most visited aquariums; plush marine animals top sellers",
     "Multiple", "Shedd Branded",
     "2M+ annual visitors; penguin/dolphin/whale plush are top sellers",
     85, "Strong gift shop revenue; marine animal plush in continuous demand",
     "Need realistic marine animal plush; eco-friendly materials",
     "Animal Plush (marine species), Eco-Friendly Plush",
     "2,000-5,000 pcs/year", "MEDIUM"],

    ["Georgia Aquarium", "georgiaaquarium.org", "United States",
     "225 Baker Street NW, Atlanta, GA 30313",
     "Not Verified", "Retail Merchandise Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 100M+", "500+", "19 (est. 2005)", "Aquarium Merchandise, Plush, Gifts",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Aquarium Visitors, Atlanta Tourists", "USD 10-35",
     "World's largest aquarium by volume; massive gift shop", "Multiple", "Georgia Aquarium Branded",
     "World's largest aquarium; 3M+ visitors; whale shark plush is iconic seller",
     85, "3M+ annual visitors; strong gift shop plush sales",
     "Need marine animal plush; custom whale shark plush opportunity",
     "Animal Plush (marine), Custom Branded Plush",
     "2,000-5,000 pcs/year", "MEDIUM"],

    ["National Aquarium Baltimore", "aqua.org", "United States",
     "501 E Pratt Street, Baltimore, MD 21202",
     "Not Verified", "Gift Shop Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 50M+", "300+", "45 (est. 1981)", "Aquarium Merchandise, Plush, Conservation Products",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Aquarium Visitors, Baltimore Tourists", "USD 8-25",
     "Major US aquarium; conservation-focused gift shop", "Multiple", "National Aquarium Branded",
     "Major East Coast aquarium; conservation-themed merchandise; eco plush priority",
     84, "Conservation messaging = eco-friendly plush opportunity",
     "Need recycled/sustainable plush; marine species; ASTM certified",
     "Eco-Friendly Animal Plush, Marine Species Plush",
     "1,000-3,000 pcs/year", "MEDIUM"],

    ["Houston Zoo", "houstonzoo.org", "United States",
     "6200 Hermann Park Dr, Houston, TX 77030",
     "Not Verified", "Retail Merchandise Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 50M+", "400+", "104 (est. 1922)", "Zoo Merchandise, Plush Animals",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Zoo Visitors, Houston Families", "USD 8-25",
     "One of most visited US zoos; strong gift shop operation", "Multiple", "Houston Zoo Branded",
     "2.5M+ annual visitors; Top 10 most visited US zoo",
     84, "High visitor count drives strong plush sales",
     "Need diverse animal plush range; competitive pricing",
     "Animal Plush (zoo species)", "2,000-5,000 pcs/year", "MEDIUM"],

    ["Woodland Park Zoo", "zoo.org", "United States",
     "5500 Phinney Ave N, Seattle, WA 98103",
     "Not Verified", "Gift Shop Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 30-50M", "300+", "126 (est. 1899)", "Zoo Merchandise, Plush Animals",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Zoo Visitors, Seattle Families", "USD 8-25",
     "Major Pacific NW zoo; uses MuzeMerch for online gift shop", "Multiple", "WPZ Branded",
     "Major Seattle zoo; active online gift shop partnership with MuzeMerch",
     83, "Active gift shop program; plush animals are core sellers",
     "Need realistic animal plush; eco-friendly preferred",
     "Animal Plush (zoo species), Eco-Friendly Plush",
     "1,000-3,000 pcs/year", "MEDIUM"],

    ["American Museum of Natural History", "amnh.org", "United States",
     "Central Park West at 79th Street, New York, NY 10024",
     "Not Verified", "Retail Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 200M+", "1,000+", "155 (est. 1869)", "Museum Merchandise, Plush, Educational",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Museum Visitors, NYC Tourists, Families", "USD 10-35",
     "Iconic NYC museum; 5M+ visitors/year; dinosaur plush top sellers", "Multiple", "AMNH Branded",
     "5M+ annual visitors; iconic museum shop; dinosaur/animal plush best sellers",
     86, "5M+ visitors drives massive gift shop revenue; plush is top category",
     "Need dinosaur and wildlife plush; educational angle; ASTM certified",
     "Animal Plush (dinosaurs, mammals), Educational Plush",
     "3,000-10,000 pcs/year", "MEDIUM-HIGH"],

    ["Australian Museum", "australian.museum", "Australia",
     "1 William Street, Sydney NSW 2010, Australia",
     "Not Verified", "Retail Manager", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "AUD 30-50M", "200+", "196 (est. 1827)", "Museum Merchandise, Plush, Educational",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Museum Visitors, Sydney Tourists, Families", "AUD 10-30",
     "Australia's oldest museum; gift shop with plush animals", "Multiple", "AM Branded",
     "Australia's oldest museum; gift shop features Australian animal plush",
     83, "Australian animal plush in demand; tourism recovering",
     "Need Australian native animal plush; eco-friendly",
     "Animal Plush (Australian species), Educational Plush",
     "1,000-3,000 pcs/year", "MEDIUM"],

    ["Marriott International", "marriott.com", "United States",
     "7750 Wisconsin Avenue, Bethesda, MD 20814",
     "Not Verified", "VP Procurement - Guest Amenities", "Not Verified", "Not Verified",
     "linkedin.com/company/marriott-international", "Not Verified", "Not Verified",
     "USD 23B+", "400,000+", "96 (est. 1927)", "Hospitality, Guest Amenities, Gift Shop Plush",
     "Yes", "Multiple", "Annual Contract", "Yes", "Yes", "No",
     "Hotel Guests, Families with Children", "N/A - Amenity/Gift",
     "8,800+ hotels globally; children's welcome amenities; gift shops", "Multiple", "Marriott Branded",
     "8,800+ hotels worldwide; children's welcome plush; branded gift shop items",
     86, "8,800 properties = massive scale for children's amenity plush",
     "Need branded plush for children's welcome kits across hotel portfolio",
     "Custom Hotel Plush, Children's Welcome Amenity Plush",
     "20,000-100,000 pcs/year", "MEDIUM-HIGH - Annual contract"],

    ["Hilton Worldwide", "hilton.com", "United States",
     "7930 Jones Branch Drive, McLean, VA 22102",
     "Not Verified", "Procurement - Guest Experience", "Not Verified", "Not Verified",
     "linkedin.com/company/hilton", "Not Verified", "Not Verified",
     "USD 10B+", "400,000+", "105 (est. 1919)", "Hospitality, Guest Amenities",
     "Yes", "Multiple", "Annual Contract", "Yes", "Yes", "No",
     "Hotel Guests, Families", "N/A - Amenity",
     "7,000+ hotels; children's amenity programs", "Multiple", "Hilton Branded",
     "7,000+ hotels globally; children's amenity programs; gift shops",
     85, "Large hotel portfolio; children's welcome plush opportunity",
     "Need children's amenity plush for hotel welcome kits",
     "Custom Hotel Plush, Children's Amenity Plush",
     "10,000-50,000 pcs/year", "MEDIUM"],

    ["Four Seasons Hotels", "fourseasons.com", "United States",
     "Toronto, Canada (HQ)",
     "Not Verified", "Director of Procurement", "Not Verified", "Not Verified",
     "linkedin.com/company/four-seasons-hotels-and-resorts", "Not Verified", "Not Verified",
     "USD 5B+", "50,000+", "63 (est. 1960)", "Luxury Hospitality, Premium Guest Amenities",
     "Yes", "Multiple", "Annual Contract", "Yes", "Yes", "No",
     "Ultra-Luxury Hotel Guests", "N/A - Premium Amenity",
     "130+ luxury hotels; premium children's amenities", "Multiple", "Four Seasons Branded",
     "130+ luxury hotels; premium children's welcome plush; quality-first approach",
     84, "Premium quality required; children's luxury amenity plush",
     "Need ultra-premium plush for luxury hotel brand standards",
     "Premium Custom Plush, Luxury Children's Amenity Plush",
     "5,000-15,000 pcs/year", "MEDIUM"],

    ["Disney Cruise Line", "disneycruise.disney.go.com", "United States",
     "Celebration, FL 34747",
     "Not Verified", "Merchandise Buyer", "Not Verified", "Not Verified",
     "linkedin.com/company/the-walt-disney-company", "Not Verified", "Not Verified",
     "USD 90B+ (Disney total)", "200,000+", "97 (est. 1923)", "Cruise Merchandise, Character Plush",
     "Yes", "China, Multiple", "Continuous", "Yes", "Yes", "Yes",
     "Cruise Passengers, Families", "USD 15-40",
     "Disney fleet expanding; onboard character plush shops", "Multiple", "Disney Characters",
     "Disney fleet expanding with new ships; onboard shops with massive plush sales",
     85, "Fleet expansion = more onboard gift shop inventory needed",
     "Need licensed character plush manufacturing capacity",
     "Character Plush, Premium Gift Plush",
     "20,000-100,000 pcs/year", "MEDIUM-HIGH"],

    ["Royal Caribbean Group", "royalcaribbeangroup.com", "United States",
     "1050 Caribbean Way, Miami, FL 33132",
     "Not Verified", "VP Onboard Revenue", "Not Verified", "Not Verified",
     "linkedin.com/company/royal-caribbean-group", "Not Verified", "Not Verified",
     "USD 14B+", "100,000+", "55 (est. 1968)", "Cruise Merchandise, Onboard Retail",
     "Yes", "Multiple", "Continuous", "No", "Yes", "Yes",
     "Cruise Passengers, Families", "USD 10-30",
     "60+ ships; onboard gift shops with plush; Icon of the Seas new", "Multiple", "RCG Branded + Licensed",
     "60+ ships; Icon of the Seas largest cruise ship; expanding fleet; onboard plush shops",
     84, "Fleet expansion with largest ships ever; onboard retail growing",
     "Need branded/custom plush for expanding onboard retail operations",
     "Custom Branded Plush, Animal Plush, Cruise-Themed Plush",
     "10,000-30,000 pcs/year", "MEDIUM"],

    ["Lotte Department Store", "lotteshopping.com", "South Korea",
     "Seoul, South Korea",
     "Not Verified", "Buyer - Children's/Toys", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "KRW 30T+", "20,000+", "46 (est. 1979)", "Department Store, Toys, Baby, Gifts",
     "Yes", "Multiple", "Continuous + Seasonal", "Yes", "Yes", "Yes",
     "Korean Families, Premium Consumers", "KRW 15,000-50,000",
     "Major Korean department store chain; plush/character toys section", "Multiple", "Licensed Brands",
     "Major Korean retailer; character plush (K-pop, anime) hugely popular; premium positioning",
     84, "K-character plush market booming in Korea; department stores expanding toy sections",
     "Need quality plush manufacturer for Korean character market",
     "Character Plush, Premium Gift Plush, Baby Plush",
     "5,000-20,000 pcs/year", "MEDIUM"],

    ["Shinsegae Group", "shinsegae.com", "South Korea",
     "Seoul, South Korea",
     "Not Verified", "Buyer - Children's", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "KRW 25T+", "15,000+", "69 (est. 1955)", "Department Store, Retail, Children's, Gifts",
     "Yes", "Multiple", "Continuous", "Yes", "Yes", "Yes",
     "Korean Premium Consumers", "KRW 10,000-40,000",
     "Premium Korean retail group; expanding children's sections", "Multiple", "Licensed Brands",
     "Major Korean retail conglomerate; children's/toy sections in expansion",
     83, "Expanding children's retail sections; plush in growing demand",
     "Need quality plush at competitive pricing for Korean market",
     "Character Plush, Baby Plush, Gift Plush",
     "3,000-10,000 pcs/year", "MEDIUM"],

    ["Kiddy Palace", "kiddypalace.com.sg", "Singapore",
     "Singapore",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "SGD 20-40M", "50-100", "20+", "Baby Products, Toys, Plush, Infant Care",
     "Yes", "Multiple", "Continuous", "Yes", "Yes", "No",
     "Singapore Families, Parents", "SGD 15-50",
     "Major Singapore baby/toy retailer chain", "China, SE Asia", "Major Baby Brands",
     "Leading Singapore baby/toy retailer; plush and infant toys core category",
     84, "Baby segment growing in Singapore; infant plush in demand",
     "Need baby-safe plush; EN71/ASTM certified; competitive pricing",
     "Baby & Infant Plush, Animal Plush",
     "2,000-8,000 pcs/year", "MEDIUM"],

    ["Best Years Ltd", "bestyears.co.uk", "United Kingdom",
     "United Kingdom",
     "Not Verified", "Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 2-5M", "5-15", "10+", "Knitted Toys, Crochet Plush, Cotton Soft Toys, Baby",
     "Yes", "India, Nepal, Bangladesh", "Continuous", "Yes", "Yes", "No",
     "UK Retailers, Gift Shops, Baby Stores", "GBP 8-25",
     "EN71/CE certified; suitable from birth; machine washable; handmade aesthetic",
     "India, Nepal, Bangladesh", "Own Brand",
     "ALREADY sources from South Asia (India, Nepal, Bangladesh); EN71 tested; baby specialist",
     93, "Already sources from India/South Asia = proven supply chain; baby plush specialist",
     "Existing South Asia sourcing = WARMEST possible lead; expand product range",
     "Baby & Infant Plush, Knitted/Crochet Plush, Cotton Plush",
     "5,000-20,000 pcs/year", "VERY HIGH - Already sources from India"],

    ["Tactile Craft Supplies", "tactilecraftsupplies.co.uk", "United Kingdom",
     "United Kingdom",
     "Not Verified", "Director", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 2-5M", "5-10", "10+", "EN71 Certified Products, Craft Supplies, Plush Materials",
     "Yes - Components", "Multiple", "Continuous", "Yes", "No", "No",
     "UK Retailers, Craft Shops, Schools", "GBP 5-15",
     "Biggest supplier of EN71 certified products in Europe", "Multiple", "Own Brand",
     "Europe's BIGGEST EN71 certified product supplier; acquired Creative Craft Supplies",
     85, "EN71 certification specialist; may need plush products for range",
     "Already positioned in EN71 compliance space; natural fit for certified plush",
     "EN71 Certified Plush, Baby Plush, Craft Plush",
     "1,000-5,000 pcs/year", "MEDIUM-HIGH"],

    ["Petsmart / Petco (Pet Plush)", "petsmart.com", "United States",
     "Phoenix, AZ (PetSmart) / San Diego, CA (Petco)",
     "Not Verified", "Category Buyer - Pet Toys", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 8B+ (PetSmart)", "50,000+", "30+", "Pet Products, Pet Plush Toys",
     "Yes - Pet Plush", "China", "Continuous", "Yes", "Yes", "No",
     "Pet Owners", "USD 5-20",
     "Massive pet plush toy buyer; 3,000+ stores combined", "China, Vietnam", "Private Label + Brands",
     "3,000+ stores; pet plush toys massive category; continuous sourcing",
     87, "Pet plush toy market booming; 3,000+ stores need continuous supply",
     "Need pet-safe plush manufacturer; non-toxic materials",
     "Pet Plush Toys (dog/cat toys), Pet-Safe Stuffed Animals",
     "100,000-500,000 pcs/year", "HIGH - Adjacent market opportunity"],

    ["Chewy Inc", "chewy.com", "United States",
     "Dania Beach, Florida, USA",
     "Not Verified", "Category Manager - Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/chewy", "Not Verified", "Not Verified",
     "USD 11B+", "15,000+", "15 (est. 2011)", "Pet Products, Pet Plush Toys (Online)",
     "Yes - Pet Plush", "China", "Continuous", "Yes", "Yes", "No",
     "Pet Owners (Online)", "USD 5-20",
     "Largest online pet retailer; pet plush toys major category", "China", "Godog, Kong, PL",
     "Largest online pet retailer; plush pet toys are best-selling category",
     87, "Fastest-growing pet retailer; continuous plush pet toy demand",
     "Need pet-safe plush manufacturer; durable construction for pet toys",
     "Pet Plush Toys, Durable Stuffed Animals for Pets",
     "50,000-200,000 pcs/year", "HIGH - Adjacent market"],

    ["George at Asda (Walmart UK)", "george.com", "United Kingdom",
     "Leeds, United Kingdom",
     "Not Verified", "Buyer - Children's Toys", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "GBP 20B+ (Asda total)", "130,000+", "50+", "Clothing, Toys, Baby, Home",
     "Yes", "China", "Seasonal + Continuous", "Yes", "No", "Yes",
     "UK Value-Conscious Families", "GBP 3-12",
     "George toy range in 600+ Asda stores; private label plush", "China, Bangladesh", "George at Asda",
     "600+ Asda stores; George private label toy/plush range; value price point",
     87, "Private label only for toys = continuous sourcing need; 600+ stores",
     "Need value-priced private label plush; EN71 certified",
     "Value Plush, Baby Plush, Seasonal Collections",
     "50,000-200,000 pcs/year", "HIGH - Private label buyer"],

    ["Primark (Associated British Foods)", "primark.com", "United Kingdom",
     "Dublin, Ireland (HQ); Global operations",
     "Not Verified", "Buyer - Kidswear & Accessories", "Not Verified", "Not Verified",
     "linkedin.com/company/primark", "Not Verified", "Not Verified",
     "GBP 9B+", "70,000+", "55 (est. 1969)", "Fashion, Accessories, Licensed Plush, Seasonal",
     "Yes", "China, India, Bangladesh", "Seasonal", "Yes", "No", "Yes",
     "Value-Fashion Consumers, Young Adults", "GBP 3-10",
     "400+ stores; Disney/character plush at value pricing; India sourcing established",
     "China, India, Bangladesh, Turkey", "Licensed Characters (Disney, etc.)",
     "400+ stores globally; ALREADY sources from India; character plush best sellers",
     89, "Already sources from India; 400+ stores; character plush at value price hugely popular",
     "Existing India sourcing relationship = warm lead; plush at ultra-value pricing",
     "Character Plush, Seasonal Plush, Value Plush Collections",
     "100,000-500,000 pcs/year", "HIGH - Already sources from India"],

    ["Tesco PLC", "tesco.com", "United Kingdom",
     "Welwyn Garden City, Hertfordshire, UK",
     "Not Verified", "Buyer - Toys & Seasonal", "Not Verified", "Not Verified",
     "linkedin.com/company/tesco", "Not Verified", "Not Verified",
     "GBP 65B+", "300,000+", "106 (est. 1919)", "Grocery, Toys, Baby, Seasonal",
     "Yes", "China", "Seasonal", "Yes", "No", "Yes - Christmas, Easter",
     "UK Families", "GBP 3-15",
     "UK's largest retailer; seasonal plush in 2,600+ stores; F&F private label",
     "China, India, Bangladesh", "F&F, Licensed Brands",
     "UK's largest retailer; 2,600+ stores; seasonal toy/plush range; India sourcing existing",
     87, "2,600+ stores; seasonal plush buyer; already sources other products from India",
     "Existing India relationship for other products = warm plush introduction",
     "Seasonal Plush Collections, Baby Plush, Value Plush",
     "100,000-500,000 pcs/season", "HIGH - Existing India sourcing"],

    ["Marks & Spencer", "marksandspencer.com", "United Kingdom",
     "London, UK",
     "Not Verified", "Buyer - Children's & Baby", "Not Verified", "Not Verified",
     "linkedin.com/company/marks-and-spencer", "Not Verified", "Not Verified",
     "GBP 13B+", "60,000+", "142 (est. 1884)", "Retail, Clothing, Baby, Gifts, Seasonal",
     "Yes", "India, China, Multiple", "Seasonal + Continuous", "Yes", "No", "Yes",
     "UK Premium-Value Consumers, Baby Segment", "GBP 8-25",
     "Premium UK retailer; Spencer Bear is iconic branded plush; India sourcing major",
     "India, China, Bangladesh, Turkey", "M&S Own Brand",
     "Spencer Bear iconic brand plush; MAJOR India sourcing across categories; premium quality",
     90, "Iconic Spencer Bear plush line; HUGE existing India sourcing = warmest lead for premium",
     "Already one of India's biggest UK retail buyers; plush fits existing supply chain",
     "Premium Gift Plush, Baby Plush, Seasonal (Spencer Bear), Christmas Collections",
     "20,000-100,000 pcs/year", "VERY HIGH - Major India sourcing relationship"],

    ["Tk Maxx (TJX Companies)", "tkmaxx.com", "United Kingdom",
     "Framingham, MA (TJX HQ); Watford, UK (EU HQ)",
     "Not Verified", "Buyer - Toys & Gifts", "Not Verified", "Not Verified",
     "linkedin.com/company/tjx-companies", "Not Verified", "Not Verified",
     "USD 54B+ (TJX total)", "300,000+", "48 (est. 1976)", "Off-Price Retail, Toys, Plush, Gifts",
     "Yes", "Multiple", "Continuous/Opportunistic", "No", "No", "Yes",
     "Bargain Hunters, Families", "USD/GBP 5-15",
     "4,900+ stores globally; off-price plush buyer; deals on overstock/canceled orders",
     "Multiple", "Brand-Name Overstock",
     "4,900+ stores; off-price model = opportunistic plush buying; massive scale",
     85, "Always buying plush at off-price; good outlet for overruns",
     "Potential channel for excess inventory or value-priced direct sourcing",
     "Value Plush, Assorted Animal Plush, Gift Plush",
     "50,000-200,000 pcs/deal", "MEDIUM - Opportunistic buyer"],

    ["Selfridges", "selfridges.com", "United Kingdom",
     "400 Oxford Street, London W1A 1AB",
     "Not Verified", "Buyer - Toys & Children's", "Not Verified", "Not Verified",
     "linkedin.com/company/selfridges", "Not Verified", "Not Verified",
     "GBP 1.5B+", "5,000+", "116 (est. 1908)", "Luxury Retail, Premium Toys, Plush, Gifts",
     "Yes", "Multiple", "Continuous + Christmas", "No", "No", "Yes",
     "Luxury Consumers, Gift Buyers", "GBP 15-80",
     "Premium UK department store; Jellycat and premium plush are top sellers",
     "Multiple", "Jellycat, Steiff, Premium Brands",
     "Premium UK dept store; premium plush (Jellycat) is one of top-selling categories",
     85, "Premium plush demand growing; Jellycat phenomenon expanding category",
     "Need premium quality plush to compete in luxury gift segment",
     "Premium Gift Plush, Baby Plush, Christmas Collections",
     "3,000-10,000 pcs/year", "MEDIUM-HIGH - Premium segment"],

    ["Jellycat", "jellycat.com", "United Kingdom",
     "London, UK",
     "Not Verified", "Production/Sourcing Director", "Not Verified", "Not Verified",
     "linkedin.com/company/jellycat", "instagram.com/jellycat", "Not Verified",
     "GBP 200-400M", "200-500", "25 (est. 1999)", "Premium Designer Plush, Stuffed Animals",
     "Yes - CORE", "China, Indonesia", "Continuous", "No", "Yes", "Yes",
     "Global Premium Gift Market, All Ages", "GBP 15-65",
     "Premium plush phenomenon; global demand outstripping supply", "China, Indonesia", "Jellycat",
     "The hottest plush brand globally; demand massively outstripping supply; viral brand",
     88, "Demand outstripping manufacturing capacity; may need additional OEM partners",
     "Capacity constraint = may need new manufacturing partners; India cost advantage",
     "Premium Designer Plush, Soft Animal Plush",
     "100,000-1,000,000 pcs/year", "MEDIUM-HIGH - Capacity constrained"],

    ["Aurora World Inc", "auroragift.com", "United States",
     "Los Angeles, California, USA (US HQ); Seoul, Korea (Global HQ)",
     "Not Verified", "VP Sourcing", "Not Verified", "Not Verified",
     "linkedin.com/company/aurora-world", "Not Verified", "Not Verified",
     "USD 100-200M", "500+", "42 (est. 1981)", "Plush Toys, Stuffed Animals (CORE BUSINESS)",
     "Yes - CORE", "China, Indonesia, Vietnam", "Continuous", "Yes", "Yes", "Yes",
     "Global Retail, All Demographics", "USD 5-30",
     "One of world's largest plush companies; YooHoo, Eco Nation lines", "China, Indonesia, Vietnam", "Aurora, YooHoo, Eco Nation",
     "Top 3 global plush brand; Eco Nation line uses recycled materials; massive production",
     86, "May need additional manufacturing capacity; Eco Nation line expanding",
     "India as supplementary manufacturing base for growing eco-friendly line",
     "Eco-Friendly Plush, Animal Plush, Novelty Plush",
     "500,000-2,000,000 pcs/year", "MEDIUM - Large but established supply chain"],

    ["Hamleys (Reliance Retail)", "hamleys.com", "United Kingdom",
     "188-196 Regent Street, London W1B 5BT",
     "Not Verified", "Buyer - Plush & Soft Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/hamleys", "instagram.com/hamleys", "Not Verified",
     "GBP 50-100M", "500+", "264 (est. 1760)", "Premium Toys, Plush, Games, Gifts",
     "Yes", "Multiple", "Continuous + Seasonal", "Yes", "Yes", "Yes",
     "Tourists, Premium Gift Buyers, Families", "GBP 8-50",
     "World's oldest toy store; owned by India's Reliance Retail; expanding globally",
     "Multiple", "Premium Brands + Own Label",
     "World's oldest toy shop; OWNED BY INDIA'S RELIANCE RETAIL; global expansion underway",
     92, "Owned by India's Reliance = Indian supplier-friendly; global expansion; premium plush buyer",
     "Indian ownership = warmest possible lead; already pro-India sourcing",
     "Premium Plush, Gift Plush, Baby Plush, Own Brand Plush",
     "10,000-50,000 pcs/year", "VERY HIGH - Indian-owned (Reliance)"],

    ["Noon.com", "noon.com", "UAE",
     "Dubai, UAE",
     "Not Verified", "Category Manager - Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/noon", "Not Verified", "Not Verified",
     "USD 500M+", "1,000+", "9 (est. 2016)", "E-Commerce, Toys, Plush, Baby, Home",
     "Yes", "Multiple", "Continuous", "Yes", "Yes", "Yes",
     "UAE/KSA Online Shoppers", "AED 20-80",
     "Middle East's leading e-commerce platform; plush/toys category growing", "China, Multiple", "Multiple Brands + Own Label",
     "MENA's Amazon equivalent; plush toys growing category; expanding private label",
     87, "E-commerce platform growing rapidly; private label plush opportunity",
     "Need competitively priced plush for e-commerce; fast delivery capability",
     "Animal Plush, Character Plush, Baby Plush, Private Label",
     "5,000-20,000 pcs/year", "MEDIUM-HIGH"],

    ["Ubuy", "ubuy.com", "Kuwait",
     "Kuwait (HQ); Operations in KSA, UAE, global",
     "Not Verified", "Category Manager", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 100-200M", "500+", "10+", "Cross-Border E-Commerce, Toys, Plush",
     "Yes", "Multiple", "Continuous", "Yes", "No", "No",
     "MENA/Global Online Shoppers", "USD 10-40",
     "Cross-border e-commerce; sells plush globally; growing MENA presence", "Multiple", "Multiple Brands",
     "Cross-border e-commerce platform; sells plush in 180+ countries",
     83, "Cross-border platform expanding; plush in growing demand in MENA",
     "Need branded plush for cross-border e-commerce in MENA",
     "Animal Plush, Character Plush, Gift Plush",
     "2,000-8,000 pcs/year", "MEDIUM"],

    ["FirstCry", "firstcry.ae", "UAE",
     "Dubai, UAE (ME); Pune, India (Global HQ)",
     "Not Verified", "Category Head - Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/firstcry", "Not Verified", "Not Verified",
     "USD 500M+", "5,000+", "14 (est. 2010)", "Baby Products, Toys, Plush, Infant Care",
     "Yes", "India, China", "Continuous", "Yes", "Yes", "No",
     "Parents, Families (Baby/Infant Focus)", "AED 20-80",
     "India's largest baby products platform; expanding in UAE/GCC", "India, China", "Multiple + Own Label",
     "India's largest baby platform; ALREADY sources from India; expanding in UAE market",
     91, "INDIAN company; already has India supply chain; baby plush core category; UAE expansion",
     "Indian HQ = easiest possible relationship; baby plush is core need",
     "Baby & Infant Plush, Sensory Plush, Developmental Plush",
     "10,000-50,000 pcs/year", "VERY HIGH - Indian company, warmest lead"],

    ["BabyShop (Landmark Group)", "babyshopstores.com", "UAE",
     "Dubai, UAE",
     "Not Verified", "Buyer - Toys & Baby", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "USD 1B+", "5,000+", "30+", "Baby Products, Toys, Plush, Infant Care",
     "Yes", "India, China", "Continuous", "Yes", "Yes", "Yes",
     "GCC Families, Baby Segment", "AED 20-80",
     "200+ stores in GCC; baby plush core category; India sourcing active",
     "India, China, SE Asia", "Own Label + Brands",
     "200+ stores across GCC; baby segment leader; already sources from India",
     89, "200+ stores; India sourcing established for other products; baby plush in demand",
     "Existing India sourcing = warm lead; baby plush growing category",
     "Baby & Infant Plush, Animal Plush, Gift Plush",
     "10,000-30,000 pcs/year", "HIGH - India sourcing established"],

    ["El Corte Inglés", "elcorteingles.es", "Spain",
     "Madrid, Spain",
     "Not Verified", "Buyer - Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/el-corte-ingles", "Not Verified", "Not Verified",
     "EUR 15B+", "80,000+", "84 (est. 1940)", "Department Store, Toys, Baby, Gifts",
     "Yes", "Multiple", "Continuous + Seasonal", "Yes", "Yes", "Yes - Christmas, Three Kings",
     "Spanish Families, Premium Consumers", "EUR 8-30",
     "Spain's largest department store chain; toy department with plush section",
     "Multiple Countries", "Major Toy Brands",
     "Spain's dominant retailer; largest department store in Europe; Christmas toy season is massive",
     86, "European toy market growing; Christmas/Three Kings seasonal plush demand huge",
     "Need EN71/CE certified plush for European market; seasonal collections",
     "Seasonal Plush, Animal Plush, Baby Plush, Character Plush",
     "10,000-50,000 pcs/year", "MEDIUM-HIGH"],

    ["Galeries Lafayette", "galerieslafayette.com", "France",
     "Paris, France",
     "Not Verified", "Buyer - Children's & Toys", "Not Verified", "Not Verified",
     "linkedin.com/company/galeries-lafayette-group", "Not Verified", "Not Verified",
     "EUR 5B+", "15,000+", "131 (est. 1893)", "Luxury Department Store, Toys, Gifts",
     "Yes", "Multiple", "Continuous + Christmas", "No", "No", "Yes",
     "French Luxury Consumers, Tourists", "EUR 15-60",
     "Iconic French department store; premium toy section with plush",
     "Multiple", "Premium Brands (Jellycat, Steiff)",
     "Iconic French luxury retailer; premium plush is growing category",
     84, "Premium plush market growing in France; Jellycat effect driving category",
     "Need premium quality plush for French luxury retail",
     "Premium Gift Plush, Baby Plush, Designer Plush",
     "3,000-10,000 pcs/year", "MEDIUM"],

    ["King Jouet", "kingjouet.com", "France",
     "Voiron, Isère, France",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "EUR 500M+", "2,000+", "50+", "Toys, Plush, Games, Outdoor",
     "Yes", "China", "Continuous + Seasonal", "Yes", "Yes", "Yes - Christmas",
     "French Families", "EUR 5-25",
     "French toy retail chain; 280+ stores; plush is key category",
     "China, SE Asia", "Major Brands + PL",
     "280+ stores; France's major toy chain; plush/soft toys important category",
     85, "Major French toy chain; continuous plush sourcing for 280+ stores",
     "Need EN71/CE certified plush supplier; competitive pricing",
     "Animal Plush, Character Plush, Baby Plush, Seasonal",
     "10,000-30,000 pcs/year", "MEDIUM-HIGH"],

    ["Müller Drogerie", "mueller.de", "Germany",
     "Ulm, Germany",
     "Not Verified", "Buyer - Toys", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "EUR 5B+", "30,000+", "70+", "Drugstore, Toys, Plush, Baby, Gifts",
     "Yes", "China", "Seasonal + Continuous", "Yes", "No", "Yes",
     "German/EU Families", "EUR 5-20",
     "German drugstore chain with major toy section; 900+ stores in 8 countries",
     "China", "Private Label + Brands",
     "900+ stores; 8 countries; toy/plush section in major drug store chain; private label",
     85, "900 stores across EU; seasonal plush collections; private label sourcing",
     "Need private label plush manufacturer; EN71/CE certified; competitive",
     "Seasonal Plush, Baby Plush, Value Collections",
     "20,000-80,000 pcs/year", "MEDIUM-HIGH"],

    ["Rossmann", "rossmann.de", "Germany",
     "Burgwedel, Germany",
     "Not Verified", "Buyer - Non-Food/Seasonal", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "EUR 12B+", "50,000+", "52 (est. 1972)", "Drugstore, Seasonal Toys, Baby, Plush",
     "Yes", "China", "Seasonal", "Yes", "No", "Yes",
     "German/EU Families", "EUR 3-15",
     "Major EU drug store chain; 4,600+ stores; seasonal toy/plush range",
     "China", "Private Label",
     "4,600+ stores in Europe; seasonal plush; private label; massive reach",
     84, "4,600 stores; seasonal plush buyer; private label only",
     "Need cost-competitive PL plush; EN71/CE critical",
     "Seasonal Plush, Baby Plush, Value Plush",
     "50,000-200,000 pcs/season", "MEDIUM-HIGH - Volume buyer"],

    ["Action (Dutch Discount Retailer)", "action.com", "Netherlands",
     "Zwaagdijk-Oost, Netherlands",
     "Not Verified", "Buyer - Toys & Seasonal", "Not Verified", "Not Verified",
     "linkedin.com/company/action-nederland", "Not Verified", "Not Verified",
     "EUR 11B+", "70,000+", "31 (est. 1993)", "Discount Retail, Toys, Plush, Seasonal",
     "Yes", "China", "Seasonal Rotations", "Yes", "No", "Yes",
     "EU Value Shoppers", "EUR 1-5",
     "Fastest growing EU retailer; 2,500+ stores; 12 countries; ultra-value plush",
     "China", "Private Label Only",
     "Fastest growing EU retailer; 2,500+ stores; 12 countries; seasonal plush at ultra-value",
     87, "Europe's fastest growing retailer; 2,500+ stores; seasonal plush rotations",
     "Need ultra-competitive pricing for extreme value retail; EN71/CE",
     "Value Plush, Mini Plush, Seasonal Collections",
     "100,000-500,000 pcs/season", "HIGH - Fastest growing EU retailer"],

    ["Zeeman", "zeeman.com", "Netherlands",
     "Alphen aan den Rijn, Netherlands",
     "Not Verified", "Buyer", "Not Verified", "Not Verified",
     "Not Verified", "Not Verified", "Not Verified",
     "EUR 1B+", "10,000+", "57 (est. 1967)", "Value Fashion, Baby, Toys, Plush",
     "Yes", "Multiple incl India", "Seasonal", "Yes", "No", "Yes",
     "EU Value Consumers, Baby Segment", "EUR 2-8",
     "Dutch value retailer; 1,300+ stores in 7 countries; baby/children's plush",
     "India, Bangladesh, China, Turkey", "Own Brand",
     "1,300+ stores; 7 countries; ALREADY sources from India; baby plush range",
     88, "Already sources from India = warm lead; value baby plush growing",
     "Existing India sourcing relationship; baby/children's plush fits existing supply chain",
     "Baby Plush, Value Plush, Children's Plush",
     "20,000-80,000 pcs/year", "HIGH - Already sources from India"],
]
